/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package layouts;

/**
 *
 * @author Usuario
 */
public class BorderLayout extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public BorderLayout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout(10, 10));

        jButton1.setText("jButton1");
        add(jButton1, java.awt.BorderLayout.CENTER);

        jButton2.setText("jButton2");
        add(jButton2, java.awt.BorderLayout.PAGE_START);

        jButton3.setText("jButton3");
        add(jButton3, java.awt.BorderLayout.LINE_START);

        jButton4.setText("jButton4");
        add(jButton4, java.awt.BorderLayout.LINE_END);

        jButton5.setText("jButton5");
        add(jButton5, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    // End of variables declaration//GEN-END:variables
}
